token: "YOUR_TOKEN_HERE"

contests:
      - "atcoder"
      - "codechef"
      - "codeforces"
      - "leetcode"
      - "topcoder"
      - "google"

ics_urls:
        atcoder: "https://calendar.google.com/calendar/ical/vdobhfoodrv59522b684lhfs7c%40group.calendar.google.com/public/basic.ics",
        codechef: "https://calendar.google.com/calendar/ical/ogc7qt4hlg454ggkj9o6ttqnq8%40group.calendar.google.com/public/basic.ics",
        codeforces: "https://calendar.google.com/calendar/ical/br1o1n70iqgrrbc875vcehacjg%40group.calendar.google.com/public/basic.ics",
        leetcode: "https://calendar.google.com/calendar/ical/tlvovsip3t3045rnkq0rt7d77c%40group.calendar.google.com/public/basic.ics",
        topcoder: "https://calendar.google.com/calendar/ical/qshn4jb7pq3f8l46nvvilj5c6o%40group.calendar.google.com/public/basic.ics",
        google: "https://calendar.google.com/calendar/ical/7qk9j0n6sa9hkc6hfgiho0m6og%40group.calendar.google.com/public/basic.ics",


roles:
        atcoder: 837746179138912307
        codechef: 835477747840974868
        codeforces: 835477747840974868
        codingame: 1004493089748033716
        google: 835480582384910366
        hackerrank: 1004493385396142110
        leetcode: 837745978378682448
        yukicoder: 837746728781611038
        admin: 1004491031628230756

channels:
        atcoder: 1001140362577985546
        codechef: 1004380321715847280
        codeforces: 1001140349776953464
        codingame: 1001140376901533796
        google: 1001140387580235877
        hackerrank: 1003419681450885312
        leetcode: 1003419750350717079
        topcoder: 1003419566917025814

display:
        atcoder: "[AtCoder]"
        codechef: "[CodeChef]"
        codeforces: "[Codeforces]"
        google: "[Google]"
        hackerrank: "[HackerRank]"
        leetcode: "[LeetCode]"
        topcoder: "[TopCoder]"

